coverage:
  precision: 2
  round: down
  range: "70...95"
  status:
    project:
      default:
        enabled: yes
        target: auto
        if_no_uploads: error
    patch:
      default:
        enabled: yes
        target: 100%
        if_no_uploads: error
    changes:
      default:
        enabled: yes
        if_no_uploads: error
  notify:
    slack:
      default:
        url: https://hooks.slack.com/services/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
        attachments: "sunburst, diff"
comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
